spring.application.name=ritmo

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Springdoc OpenApi 3.1 & Swagger 3
springdoc.swagger-ui.path=/ritmo.html
springdoc.api-docs.path=/docs-ritmo
springdoc.packagesToScan=src/main/java/com/wellness/ritmo/api/controller